import { Transaction, TransactionScope, TransactionType, PriorityBill } from "./types";

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-demo-1",
    date: "2026-06-15",
    description: "Honorários Contratuais - Processo Revisional Banco Alfa",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Honorários Contratuais",
    amount: 14500.00,
    paymentMethod: "Pix",
    notes: "Honorários contratuais iniciais pagos em Pix à vista.",
  },
  {
    id: "tx-demo-2",
    date: "2026-06-14",
    description: "Aluguel e Condomínio - Sala 402 Ed. Fórum",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Aluguel e Condomínio do Escritório",
    amount: 3200.00,
    paymentMethod: "Boleto",
    notes: "Locação da sede física do escritório advocatício.",
  },
  {
    id: "tx-demo-3",
    date: "2026-06-13",
    description: "Honorários de Sucumbência - Processo Trabalhista CPT",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Honorários de Sucumbência",
    amount: 6800.00,
    paymentMethod: "TED",
    notes: "Alvará judicial expedido pela 2ª Vara do Trabalho.",
  },
  {
    id: "tx-demo-4",
    date: "2026-06-12",
    description: "Supermercado Pão de Açúcar - Compras do Mês (Pessoal)",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PERSONAL,
    category: "Alimentação e Supermercados",
    amount: 852.40,
    paymentMethod: "Cartão de Crédito",
    notes: "Uso de cartão corporativo para compras do apartamento de família. Mistura detectada pela IA.",
    isAiCategorized: true, // This marks it as personal leaks into corporate accounts
  },
  {
    id: "tx-demo-5",
    date: "2026-06-10",
    description: "Consultoria Trabalhista Preventiva - Logística Express",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Consultoria e Pareceres",
    amount: 3500.00,
    paymentMethod: "Pix",
    notes: "Contrato de assessoria corporativa de terceiro setor.",
  },
  {
    id: "tx-demo-6",
    date: "2026-06-08",
    description: "Retirada de Pró-labore Dr. Gustavo Dantas",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Equipe, Associados e Pró-labore",
    amount: 5000.00,
    paymentMethod: "Pix",
    notes: "Retirada padrão do sócio majoritário.",
  },
  {
    id: "tx-demo-7",
    date: "2026-06-08",
    description: "Recebimento de Retirada Pró-labore (Pessoal)",
    type: TransactionType.REVENUE,
    scope: TransactionScope.PERSONAL,
    category: "Retirada de Pró-labore/Lucros",
    amount: 5000.00,
    paymentMethod: "Pix",
    notes: "Alimentação do caixa pessoal vindo do escritório da advocacia.",
  },
  {
    id: "tx-demo-8",
    date: "2026-06-07",
    description: "Sistemas Judiciais e LegalTech - Astrea",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Sistemas Judiciais e Softwares (LegalTech)",
    amount: 289.90,
    paymentMethod: "Cartão",
    notes: "Assinatura mensal do software de gestão de processos.",
  },
  {
    id: "tx-demo-9",
    date: "2026-06-05",
    description: "Escritório de Contabilidade - Contabilizei PJ",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Material de Escritório, Internet e Luz",
    amount: 197.00,
    paymentMethod: "Pix",
    notes: "Contabilidade PJ mensal.",
  },
  {
    id: "tx-demo-10",
    date: "2026-06-04",
    description: "Restaurante Rubaiyat - Jantar de Networking PF (Cartão PJ)",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PERSONAL,
    category: "Lazer, Viagens e Hobbies",
    amount: 450.00,
    paymentMethod: "Cartão PJ",
    notes: "Refeição pessoal debitada irregularmente na conta do escritório.",
    isAiCategorized: true,
  },
  {
    id: "tx-demo-11",
    date: "2026-06-03",
    description: "Internet Fibra e Telefonia Móvel Vivo Empresas",
    type: TransactionType.EXPENSE,
    scope: TransactionScope.PROFESSIONAL,
    category: "Material de Escritório, Internet e Luz",
    amount: 320.00,
    paymentMethod: "Boleto",
    notes: "Plano mensal de telefonia e internet fixa.",
  }
];

export const INITIAL_PRIORITY_BILLS: PriorityBill[] = [
  // --- SUBGRUPO R$ 3.971,09 ---
  {
    id: "pb-1-1",
    description: "Baia Maravilha",
    amount: 780.80,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Parcelamento baia lazer familiar",
  },
  {
    id: "pb-1-2",
    description: "Ressarcimento Roneiderson",
    amount: 1500.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Honorários associado de processo",
  },
  {
    id: "pb-1-3",
    description: "Seguro Solidy",
    amount: 150.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Seguro automotivo particular",
  },
  {
    id: "pb-1-4",
    description: "Rastreador Raiotek",
    amount: 60.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-5",
    description: "Entrada Acordo CAP",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G1",
  },
  {
    id: "pb-1-6",
    description: "Ressarcimento Gedson",
    amount: 750.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Diligências de audiências de junho",
  },
  {
    id: "pb-1-7",
    description: "Plano de Saúde Seguros Unimed",
    amount: 480.29,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G1",
    notes: "Convênio coparticipativo escritório",
  },

  // --- SUBGRUPO R$ 3.032,00 ---
  {
    id: "pb-2-1",
    description: "Maravilha maio",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-2",
    description: "Empréstimo Luan",
    amount: 200.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-3",
    description: "Curso Advocacia Odontológica Pai",
    amount: 250.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G2",
    notes: "Capacitação técnica direito na saúde",
  },
  {
    id: "pb-2-4",
    description: "Empréstimo PAI",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-5",
    description: "Excursão Barretos",
    amount: 500.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-6",
    description: "Karavella",
    amount: 250.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-7",
    description: "Cerveja Folia Facebeer",
    amount: 432.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },
  {
    id: "pb-2-8",
    description: "Mula Katarina",
    amount: 400.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G2",
  },

  // --- SUBGRUPO R$ 1.516,00 ---
  {
    id: "pb-3-1",
    description: "Contabilizei maio",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-2",
    description: "Contabilizei junho",
    amount: 197.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Honorários contabilidade PJ escritório",
  },
  {
    id: "pb-3-3",
    description: "Acordo OAB abril",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-4",
    description: "Acordo OAB maio",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-5",
    description: "Acordo OAB junho",
    amount: 161.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Parcelamento OAB Secional",
  },
  {
    id: "pb-3-6",
    description: "Plano TIM",
    amount: 130.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },
  {
    id: "pb-3-7",
    description: "Plano VIVO maio",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-8",
    description: "Plano VIVO junho",
    amount: 160.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "PAGAR",
    groupType: "G3",
    notes: "Telefonia móvel escritório",
  },
  {
    id: "pb-3-9",
    description: "Óculos Pai 1 de 7",
    amount: 199.00,
    scope: TransactionScope.PERSONAL,
    status: "PAGAR",
    groupType: "G3",
  },

  // --- ESPERAR (Total: R$ 6.507,00) ---
  {
    id: "pb-w-1",
    description: "Repasse Brunner",
    amount: 1800.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Parceria divisão de processos",
  },
  {
    id: "pb-w-2",
    description: "Óculos e Lente",
    amount: 1840.00,
    scope: TransactionScope.PERSONAL,
    status: "ESPERAR",
    groupType: "WAIT",
  },
  {
    id: "pb-w-3",
    description: "Ajustes VextriaHub",
    amount: 2000.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Prestação serviços TI LegalTech",
  },
  {
    id: "pb-w-4",
    description: "Mentoria Dr Antônio",
    amount: 867.00,
    scope: TransactionScope.PROFESSIONAL,
    status: "ESPERAR",
    groupType: "WAIT",
    notes: "Mentoria de gestão estratégica",
  },
];
